#!/bash

[[ ${BPAN_ROOT-} ]] || {
  (
    echo "Tests require BPAN to be installed."
    echo "See https://github.com/bpan-org/bpan"
  ) >&2
  exit 1
}

source "$BPAN_ROOT/lib/bpan.bash" --

bpan:source bashplus --
bpan:source test-tap

test-errors() {
  while read -r cmd && read -r msg; do
    cmd=${cmd#> }
    is "$(BPAN_TESTING=1 $cmd 2>&1)" "$msg" \
      "'$cmd' fails with: $msg"
  done
}

test-install-setup() {
  export BPAN_INSTALL=$PWD//test/local
  rm -fr "$BPAN_INSTALL"
  mkdir -p "$BPAN_INSTALL"

  I=$BPAN_INSTALL

  trap test-install-teardown exit
}

test-install-teardown() (
  rm -fr ./test/local
)
