#!/bash

# DO NOT EDIT. GENERATED BY BPAN.

[[ ${BPAN_ROOT-} ]] || {
  (
    echo "Tests require BPAN to be installed."
    echo "See https://github.com/bpan-org/bpan"
  ) >&2
  exit 1
}

source "$BPAN_ROOT/lib/bpan.bash" --

bpan:source bashplus --
bpan:source test-tap

export PATH=$PWD/lib:$PATH

# Add any custom initialization to a test/init-local file.
if [[ -f test/init-local ]]; then
  source test/init-local
fi
