# DO NOT EDIT. GENERATED BY BPAN.

SHELL := bash

ifdef BPAN_ROOT
    BPAN_CMDS := $(shell bpan -q cmds)
    BPAN_CMDS := $(filter-out add bump config init install new search test uninstall,$(BPAN_CMDS))
endif

b ?=
o ?=
v ?=
test ?= test/

.SECONDEXPANSION:
.DELETE_ON_ERROR:

default::



ifdef BPAN_CMDS

$(BPAN_CMDS)::
	bpan$(if $b, $b) $@$(if $o, $o)

.PHONY: test
test::
	prove$(if $v, -v) $(test)

bump::
	bpan $@ --push

endif



# Add custom Makefile rules to a '.bpan/local.mk' file.
ifneq (,$(wildcard .bpan/local.mk))
include .bpan/local.mk
endif

ifndef BPAN_ROOT
    $(info BPAN_ROOT variable not set)
    $(info Makefile requires BPAN to be installed)
    $(info See: https://github.com/bpan-org/bpan)
    $(error ERROR)
endif
