# DO NOT EDIT. GENERATED BY BPAN.

SHELL := bash

ifndef BPAN_ROOT
$(info BPAN_ROOT variable not set)
$(info Makefile requires BPAN to be installed)
$(info See: https://github.com/bpan-org/bpan)
$(error ERROR)
endif

BPAN_CMDS := $(shell bpan -q cmds | grep -v 'bump\|test')

o ?=
test ?= test/

.SECONDEXPANSION:
.DELETE_ON_ERROR:

default::

$(BPAN_CMDS)::
	bpan $@ $o

.PHONY: test
test::
	prove -v $(test)

bump::
	bpan $@ --push

# Add custom Makefile rules to a '.bpan/local.mk' file.
ifneq (,$(wildcard .bpan/local.mk))
include .bpan/local.mk
endif
