#!/usr/bin/env bash

source /bpan/.rc
source /bpan/lib/bpan.bash --

main() (
  if [[ ${BPAN_TEST_BASH_VERSION-} ]]; then
    export PATH=/bash-$BPAN_TEST_BASH_VERSION/bin:$PATH
  fi
  bpan test "$@"
)

main "$@"
