#!/usr/bin/env bash

if [[ ${1-} == --version ]]; then
  echo 0.0.0
  exit
fi

cat >/dev/null

cat <<'...'
{
  "blocks": [
    {
      "t": "Para",
      "c": [
        {
          "t": "Str",
          "c": "foo"
        }
      ]
    }
  ],
  "pandoc-api-version": [
    1,
    20
  ],
  "meta": {}
}
...
